### ISSUE TITLE
Load policy from local OCI store

### ISSUE THREAD

**Issue by ronenh** [aserto-dev/topaz#63]
```[tasklist]
### Tasks
- [x] Provide a way to configure topaz with an image from a local OCI store.
- [x] Run authorizer with image from a local OCI store.
```

```[tasklist]
### Initial PoC:
- [ ] https://github.com/aserto-dev/runtime/pull/37
- [ ] https://github.com/aserto-dev/topaz/pull/65
```

**Comment by carabasdaniel** [comment]
The replace `replace github.com/spf13/afero => github.com/spf13/afero v1.9.5` fixes medium severity CVE in runtime PR.

**Comment by carabasdaniel** [comment]
Release https://github.com/aserto-dev/topaz/releases/tag/v0.20.29
